### ISSUE TITLE
Error in colMeans(xt) : 'x' must be an array of at least two dimensions

### ISSUE THREAD

**Issue by komalsrathi** [ajitjohnson/imsig#4]
Hi,

I am using the imsig function on a data frame with the dimensions: 3073x74 but I am getting an error:

```
cell_abundance <- imsig(exp = dat)
Error in colMeans(xt) : 'x' must be an array of at least two dimensions
```

The input matrix looks like this:
```
head(dat)
            850_1   850_12   850_15   850_16   850_19
HSP90AB1 45692.00 41446.00 41257.00 44824.00 45158.00
PKM      47462.64 25530.66 12935.48 13589.50 18485.20
RPSA     16776.18 37067.86 17202.98 17110.53 26381.38
ANXA2    14280.00 17008.00  8279.00  9320.00  8841.00
RPL4     13009.00 27260.00 13832.00 14174.00 20250.00
PTMA     19532.58 18214.23 19824.99 17947.67 18417.27
```

Let me know if you need more information.

**Comment by ajitjohnson** [comment]
Hi Komal,

your 'dat' looks fine. Just wondering if it is missing a number of imsig genes (since you have got only 3073 genes in your dataset).

Does the function work with the example dataset (attached with the package)?
imsig (exp = exp, r = 0.7)

If you can send me a subset of your data with all genes (3073), I can try and troubleshoot it.

Best,
Ajit.

**Comment by komalsrathi** [comment]
Hi Ajit,

I tried it with another dataset with 13,530 genes and it is still throwing the same error. I am attaching a drive link to the RData object for the matrix. Can you try to run the function against it and let me know the issue?

https://drive.google.com/open?id=1bC_ecuia7L4jw49P3aB9sNjdUK0Mz7d5

Thanks
Komal

**Comment by ajitjohnson** [comment]
Hi Komal,

Thank you for the data. As I suspected, the function failed because there was not enough genes mapping to the imsig signature. For each cell type, it requires at least 2 genes to overlap between the users' dataset and imsig (note in the publication we mention that it is good to have >75% overlap). In your dataset, there was only one gene mapping to the NK cell imsig signature. 

Unfortunately, based on the way the function is currently written, it assumes that there is at least an overlap of 2 genes in every signature. I will have to re-write the function such that it skips the enumeration of cell types with a poor overlap. 

The only workaround, for now, is to manually identify cell types that have <2 genes of overlap and add dummy values. For e.g. if you have only one gene in NK cells, look at the attached file and check of NK cell genes and add dummy expression values to them. Then disregard the relative abundance of those from the final output. 

Hope it helps.

Best,
Ajit.
[imsig genes.txt](https://github.com/ajitjohnson/imsig/files/2756964/imsig.genes.txt)

**Comment by komalsrathi** [comment]
Ok, that makes sense. Thanks for the quick response!

**Comment by komalsrathi** [comment]
I just tested this again by adding 3 NK-cells specific genes to the previous dataset but still getting the same error. Here is the drive link to the updated dataset where you will see the dummy values in bottom three rows: https://drive.google.com/open?id=1ghvTcWCEa16ucnvF3yS3qLDDu6QSOZaq

**Comment by ajitjohnson** [comment]
Hi Komal,

You will need to add real random dummy values. The way I did it was by copying values from 3 other random genes. If you add '0' to all, the correlation calculation within the function will fail as this is a correlation based approach. 

Also, I would recommend having all the values in natural scale and not having negative values. 

Hope this helps.

Best,
Ajit.

**Comment by komalsrathi** [comment]
Ah okay. I'll give it a try. Thanks!
